name: CDK Deployment

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      aws-region:
        required: true
        type: string

#permissions:
#  id-token: write 
#  contents: read 

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-duration-seconds: 900
          role-to-assume: ${{ inputs.role-to-assume }}

      - name: Install dependencies
        run: npm install

      - name: Synth stack
        run: npx cdk synth

      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never
