on: [push, workflow_dispatch]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-1
          role-duration-seconds: 1800
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::552193173995:role/OtherRepoGithubRole
      - name: Install dependencies
        run: npm install
      - name: Synth stack
        run: npx cdk synth
      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never
